; Spicetify - Crimson Temple
; Location: ~/.config/spicetify/Themes/CrimsonTemple/color.ini
; Colors are hex WITHOUT the #.

[Base]
text               = d8d4ce
subtext            = 8a8681
main               = 131314
main-elevated      = 1d2224
highlight          = 2c3335
highlight-elevated = 2c3335
sidebar            = 0d0d0e
player             = 131314
card               = 1d2224
shadow             = 000000
selected-row       = d8d4ce
button             = e9445e
button-active      = f06a80
button-disabled    = 4a5255
tab-active         = 2c3335
notification       = 5c0f2a
notification-error = e9445e
misc               = 8a8681
