# Hypridle - auto-lock
# Location: ~/.config/hypr/hypridle.conf

general {
    # Only start hyprlock if it isn't already running
    lock_cmd = pidof hyprlock || hyprlock
    # Lock before the computer goes to sleep
    before_sleep_cmd = loginctl lock-session
}

# Lock after 10 minutes of no keyboard/mouse input
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}
